from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Core event dataclasses
# ---------------------------------------------------------------------------

@dataclass(slots=True)
class EEGChunkEvent:
    """A single windowed chunk of multi-channel EEG data."""

    patient_id: str
    session_id: str
    event_time: str
    site_id: str
    channel_count: int
    sampling_rate_hz: float
    window_seconds: float
    source_uri: str
    fingerprint: str = ""

    def __post_init__(self) -> None:
        if not self.fingerprint:
            self.fingerprint = compute_fingerprint(self.to_dict())

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> EEGChunkEvent:
        return cls(
            patient_id=data["patient_id"],
            session_id=data["session_id"],
            event_time=data["event_time"],
            site_id=data["site_id"],
            channel_count=int(data["channel_count"]),
            sampling_rate_hz=float(data["sampling_rate_hz"]),
            window_seconds=float(data["window_seconds"]),
            source_uri=data.get("source_uri", ""),
            fingerprint=data.get("fingerprint", ""),
        )


@dataclass(slots=True)
class EHREvent:
    """An Electronic Health Record update event."""

    patient_id: str
    encounter_id: str
    event_time: str
    event_type: str
    source_system: str
    version: int
    payload: dict[str, Any]
    fingerprint: str = ""

    def __post_init__(self) -> None:
        if not self.fingerprint:
            self.fingerprint = compute_fingerprint(self.to_dict())

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> EHREvent:
        return cls(
            patient_id=data["patient_id"],
            encounter_id=data["encounter_id"],
            event_time=data["event_time"],
            event_type=data["event_type"],
            source_system=data.get("source_system", ""),
            version=int(data.get("version", 1)),
            payload=data.get("payload", {}),
            fingerprint=data.get("fingerprint", ""),
        )


@dataclass(slots=True)
class FeatureEvent:
    """Computed features for a patient session window."""

    patient_id: str
    session_id: str
    window_end: str
    anomaly_score: float
    signal_quality_score: float
    feature_values: dict[str, float]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> FeatureEvent:
        return cls(
            patient_id=data["patient_id"],
            session_id=data["session_id"],
            window_end=data["window_end"],
            anomaly_score=float(data["anomaly_score"]),
            signal_quality_score=float(data["signal_quality_score"]),
            feature_values=data.get("feature_values", {}),
        )


@dataclass(slots=True)
class AlertEvent:
    """An anomaly alert generated by the serving layer."""

    patient_id: str
    session_id: str
    alert_time: str
    severity: str
    anomaly_score: float
    explanation: str
    alert_id: str = ""

    def __post_init__(self) -> None:
        if not self.alert_id:
            self.alert_id = compute_fingerprint(
                {"patient_id": self.patient_id, "alert_time": self.alert_time, "severity": self.severity}
            )[:16]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AlertEvent:
        return cls(
            patient_id=data["patient_id"],
            session_id=data["session_id"],
            alert_time=data["alert_time"],
            severity=data["severity"],
            anomaly_score=float(data["anomaly_score"]),
            explanation=data.get("explanation", ""),
            alert_id=data.get("alert_id", ""),
        )


@dataclass(slots=True)
class DLQRecord:
    """A dead-letter queue record capturing a failed event."""

    original_topic: str
    original_payload: dict[str, Any]
    error_reason: str
    error_timestamp: str = ""
    retry_count: int = 0
    fingerprint: str = ""

    def __post_init__(self) -> None:
        if not self.error_timestamp:
            self.error_timestamp = datetime.now(timezone.utc).isoformat()
        if not self.fingerprint:
            self.fingerprint = compute_fingerprint(self.original_payload)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DLQRecord:
        return cls(
            original_topic=data["original_topic"],
            original_payload=data["original_payload"],
            error_reason=data["error_reason"],
            error_timestamp=data.get("error_timestamp", ""),
            retry_count=int(data.get("retry_count", 0)),
            fingerprint=data.get("fingerprint", ""),
        )


@dataclass(slots=True)
class BronzeEEGRecord:
    """A bronze-layer EEG record with ingestion metadata."""

    patient_id: str
    session_id: str
    event_time: str
    site_id: str
    channel_count: int
    sampling_rate_hz: float
    window_seconds: float
    source_uri: str
    fingerprint: str
    ingestion_time: str = ""
    date: str = ""

    def __post_init__(self) -> None:
        if not self.ingestion_time:
            self.ingestion_time = datetime.now(timezone.utc).isoformat()
        if not self.date:
            try:
                self.date = self.event_time[:10]
            except (TypeError, IndexError):
                self.date = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_eeg_event(cls, event: EEGChunkEvent) -> BronzeEEGRecord:
        return cls(
            patient_id=event.patient_id,
            session_id=event.session_id,
            event_time=event.event_time,
            site_id=event.site_id,
            channel_count=event.channel_count,
            sampling_rate_hz=event.sampling_rate_hz,
            window_seconds=event.window_seconds,
            source_uri=event.source_uri,
            fingerprint=event.fingerprint,
        )


@dataclass(slots=True)
class BronzeEHRRecord:
    """A bronze-layer EHR record with ingestion metadata."""

    patient_id: str
    encounter_id: str
    event_time: str
    event_type: str
    source_system: str
    version: int
    payload: dict[str, Any]
    fingerprint: str
    ingestion_time: str = ""
    date: str = ""

    def __post_init__(self) -> None:
        if not self.ingestion_time:
            self.ingestion_time = datetime.now(timezone.utc).isoformat()
        if not self.date:
            try:
                self.date = self.event_time[:10]
            except (TypeError, IndexError):
                self.date = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_ehr_event(cls, event: EHREvent) -> BronzeEHRRecord:
        return cls(
            patient_id=event.patient_id,
            encounter_id=event.encounter_id,
            event_time=event.event_time,
            event_type=event.event_type,
            source_system=event.source_system,
            version=event.version,
            payload=event.payload,
            fingerprint=event.fingerprint,
        )


# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

def compute_fingerprint(data: dict[str, Any]) -> str:
    """Compute a SHA-256 fingerprint for deduplication.

    Non-metadata fields are serialized deterministically and hashed.
    """
    sanitized = {k: v for k, v in data.items() if k not in ("fingerprint", "ingestion_time")}
    canonical = json.dumps(sanitized, sort_keys=True, default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def to_payload(record: EEGChunkEvent | EHREvent | FeatureEvent | AlertEvent | DLQRecord) -> dict[str, Any]:
    """Convert any event record to a plain dictionary."""
    return asdict(record)


def to_json(record: EEGChunkEvent | EHREvent | FeatureEvent | AlertEvent | DLQRecord) -> str:
    """Serialize an event record to a JSON string."""
    return json.dumps(asdict(record), default=str)


def validate_required_fields(payload: dict[str, Any], required_fields: set[str]) -> list[str]:
    """Return a sorted list of field names that are missing or empty."""
    return [field for field in sorted(required_fields) if payload.get(field) in (None, "")]


EEG_REQUIRED_FIELDS: set[str] = {
    "patient_id", "session_id", "event_time", "site_id",
    "channel_count", "sampling_rate_hz",
}

EHR_REQUIRED_FIELDS: set[str] = {
    "patient_id", "encounter_id", "event_time", "event_type",
}

ALERT_REQUIRED_FIELDS: set[str] = {
    "patient_id", "session_id", "alert_time", "severity", "anomaly_score",
}
